// -------------------------------------------------------------------
// NOTICE:
// This file has been auto generated by the CMake system.
// All modifications should be done in SerializableObjects.h.tpl
// -------------------------------------------------------------------
// ALL MODIFICATIONS TO THIS FILE WILL BE LOST NEXT TIME YOU REBUILD.
// -------------------------------------------------------------------
#include <Geometry/Material.h>
#include <Resources/SDLImage.h>

