# Find all sub directories in the extensions directory
FILE(GLOB EXTERNALS_SUB_DIRECTORIES RELATIVE
     ${OE_EXTERNALS_DIR} "${OE_EXTERNALS_DIR}/*")

# If any extensions are found include them
FOREACH(SUB_DIR ${EXTERNALS_SUB_DIRECTORIES})
  SET(FULL_SUB_DIR "${OE_EXTERNALS_DIR}/${SUB_DIR}")
  IF(IS_DIRECTORY ${FULL_SUB_DIR})
    MESSAGE(STATUS "Linking in external source: ${SUB_DIR}")
    INCLUDE_DIRECTORIES(${FULL_SUB_DIR})
    SUBDIRS(${FULL_SUB_DIR})

    # Invoke setup file if present
    SET(SETUP_FILE "${FULL_SUB_DIR}/Setup.cmake")
    IF(EXISTS ${SETUP_FILE})
      SET(OE_CURRENT_EXTERNALS_DIR "${FULL_SUB_DIR}")
      INCLUDE(${SETUP_FILE})
      SET(OE_CURRENT_EXTERNALS_DIR "")
    ENDIF(EXISTS ${SETUP_FILE})
  ENDIF(IS_DIRECTORY ${FULL_SUB_DIR})
ENDFOREACH(SUB_DIR)
