# Compute the default debug flag based on build type
IF (CMAKE_BUILD_TYPE MATCHES debug)
  SET(DEFAULT_DEBUG true)
ELSE (CMAKE_BUILD_TYPE MATCHES debug)
  SET(DEFAULT_DEBUG false)
ENDIF (CMAKE_BUILD_TYPE MATCHES debug)

# Set the default if not already defined
IF(NOT DEFINED OE_DEBUG_CMAKE)
  SET(OE_DEBUG_CMAKE ${DEFAULT_DEBUG})
ENDIF(NOT DEFINED OE_DEBUG_CMAKE)
IF(NOT DEFINED OE_DEBUG_GL)
  SET(OE_DEBUG_GL ${DEFAULT_DEBUG})
ENDIF(NOT DEFINED OE_DEBUG_GL)

# OE_SAFE always defaults to "true"
IF(NOT DEFINED OE_SAFE)
  SET(OE_SAFE true)
ENDIF(NOT DEFINED OE_SAFE)
