IF(CMAKE_COMPILER_IS_GNUCXX)
  # SET (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3 -Wall -Wextra -Wno-unused-parameter")
  ADD_DEFINITIONS(-Wall -Wextra -Wno-unused-parameter -DOE_SAFE=${OE_SAFE} -DOE_DEBUG_GL=${OE_DEBUG_GL})
  # SET (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}  -fpeel-loops") # for OSX
  IF (CMAKE_BUILD_TYPE MATCHES debug)
    ADD_DEFINITIONS(-D_DEBUG)
  ENDIF (CMAKE_BUILD_TYPE MATCHES debug)
ENDIF(CMAKE_COMPILER_IS_GNUCXX)
